# Generated by Django 3.2 on 2024-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_Apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.BigIntegerField(null=True),
        ),
    ]
