# Generated by Django 3.2 on 2024-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_Apis', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='trailers'),
        ),
    ]
