# Generated by Django 3.2 on 2024-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_Apis', '0003_auto_20240330_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
